import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css';
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <nav className="navbar navbar-expand-lg navbar-dark bg-dark fixed-top position-sticky" >
        <a className="navbar-brand" href="./">
          <img src="/favicon.ico" width="30" height="30" className="d-inline-block align-top" alt="" />
          <span> CMS Midterm</span>
        </a>
        <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div className="navbar-nav">
            <a className="nav-item nav-link" href="/">Home</a>
            <a className="nav-item nav-link" href="/post">Post</a>
            <a className="nav-item nav-link" href="/category">Category</a>
            <a className="nav-item nav-link" href="/author">Author</a>
          </div>
        </div>
        {/* <form className="form-inline">
          <input className="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
          <button className="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> */}
      </nav>
      <Head>
          <title>Home Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
